// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hpxoifxeswbiqwzzhglc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhweG9pZnhlc3diaXF3enpoZ2xjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3ODk0MjMsImV4cCI6MjA3MTM2NTQyM30.EKcV7sZO9S8_UZHCI2i14Nb9ixl33-axZxs0MRwNUF0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});